### PR TITLE
WND-CHARM Python API v1.0

### PR DESCRIPTION
**Pull request by colettace**
Still need to merge in version 3.0 features and latest stuff from wndcharm/master, so don't merge yet.

This PR is the culmination of 8 months worth of work. It contains breaking API changes from previous versions. Enhancements include:

* Mammoth FeatureSet.py code broken out into individual modules, all with their own unit tests.
* Previous objects <code>FeatureSet_Discrete</code> and <code>FeatureSet_Continuous</code> merged into a single object for classification and regression called <code>FeatureSpace</code>
* API for feature calculation & classification for tiled images.
* Multichannel Feature Space specification mini-language using file list ("file of files").
* Object hierarchy and API simplified/made more clear/easier to use, using industry-standard machine learning terminology; instance attribute names are more uniform across all objects.
* Object members properly made instance attributes instead of class attributes.
* Etc.

Almost every object was renamed. Still need to finalize names for API. Please give feedback. The following list give the rough evolution of the names of objects from the C++ library -> previous python API names -> current/proposed API names:

* <code>Signatures</code> -> <code>Signatures</code> -> <code>FeatureVector</code>
* <code>TrainingSet</code> -> <code>FeatureSet</code> -> <code>FeatureSpace</code>
* individual classification -> <code>ImageClassificationResult</code> -> <code>SingleSampleClassification</code> and <code>SingleSampleRegression</code>
* <code>split</code> -> <code>BatchClassificationResult</code> -> <code>FeatureSpaceClassification</code> and <code>FeatureSpaceRegression</code>
* HTML file -> <code>BatchClassificationExperimentResult</code> -> <code>FeatureSpaceClassificationExperiment</code> and <code>FeatureSpaceRegressionExperiment</code>
* a list of feature names -> <code>FeatureVector</code> -> <code>FeatureSet</code>

Still to do for this release:
* Rebase latest stuff from wndcharm/master
* Merge the multichannel tiff reading code from @igg development branch.
* Figure out what to do with writing objects to and from pickle files.
* Update the example code in the <code>examples</code> directory.

### CODE REVIEW

**Comment by colettace** [comment]
cc: @manics @icaoberg @vuhlmann

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [ANALYSIS-OMERO-WNDCHARM-merge#570](http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-WNDCHARM-merge/570/). See the [console output](http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-WNDCHARM-merge/570/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - tests/pywndcharm_tests/test_WND5.py
    - wndcharm/FeatureSet.py

**Comment by manics** [comment]
@colettace That "Conflicting PR" message is from our automated CI build which attempts to merge all PRs for testing (looks like master has had some changes committed since you originally forked this branch). I can disable the automated message- or keep them if you think it's useful.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [ANALYSIS-OMERO-WNDCHARM-merge#571](http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-WNDCHARM-merge/571/). See the [console output](http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-WNDCHARM-merge/571/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - tests/pywndcharm_tests/test_WND5.py
    - wndcharm/FeatureSet.py

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [ANALYSIS-OMERO-WNDCHARM-merge#572](http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-WNDCHARM-merge/572/). See the [console output](http://ci.openmicroscopy.org/job/ANALYSIS-OMERO-WNDCHARM-merge/572/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - tests/pywndcharm_tests/test_WND5.py
    - wndcharm/FeatureSet.py

**Comment by colettace** [comment]
@manics Yeah I think disabling the automated message would be best, prob not ready to merge this PR until end of this month, thanks man!

**Comment by manics** [comment]
@colettace Done

**Pull request merged**
